version: '3'
services:
    laravel:
       build:
         context: .
         dockerfile: Dockerfile
       image: laravel-app
       container_name: laravel-app
       restart: unless-stopped
       working_dir: /var/www/html
       volumes:
         - .:/var/www/html
       ports:
         - 8000:80
       environment:
         - DB_HOST=laravel-app-mysql
         - DB_PORT=3306
         - DB_DATABASE=laravel
         - DB_USERNAME=root
         - DB_PASSWORD=password
    mysql:
     image: mysql:8.0
     container_name: laravel-app-mysql
     restart: unless-stopped
     ports:
       - 5505:3306
     environment:
         MYSQL_DATABASE: laravel
         MYSQL_ROOT_PASSWORD: "password"
     volumes:
       - ./mysql:/var/lib/mysql
    testingdb:
     image: mysql:8.0
     container_name: testing
     restart: unless-stopped
     ports:
       - 5050:3306
     environment:
         MYSQL_DATABASE: testing
         MYSQL_ROOT_PASSWORD: "password"